# Generated by Django 6.0.6 on 2026-07-18 05:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escaneo',
            fields=[
                ('id_escaneo', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='scanner/escaneos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('confianza', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de confianza entre 0 y 100.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reconocido', models.BooleanField(default=False)),
                ('ave_detectada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escaneos', to='catalogo.ave')),
            ],
            options={
                'verbose_name': 'escaneo',
                'verbose_name_plural': 'escaneos',
                'ordering': ['-fecha', '-id_escaneo'],
            },
        ),
    ]
