# Generated by Django 6.0.6 on 2026-07-18 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escaneo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escaneos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='escaneo',
            constraint=models.CheckConstraint(condition=models.Q(('confianza__gte', 0), ('confianza__lte', 100)), name='scanner_confianza_entre_0_y_100'),
        ),
        migrations.AddConstraint(
            model_name='escaneo',
            constraint=models.CheckConstraint(condition=models.Q(('reconocido', False), ('ave_detectada__isnull', False), _connector='OR'), name='scanner_reconocido_requiere_ave'),
        ),
    ]
