# Generated by Django 6.0.6 on 2026-07-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_ave_catalogo_activa_nombre_idx'),
        ('scanner', '0003_alter_escaneo_usuario'),
        ('usuario', '0006_sesioncuentaaplicacion_ultima_actividad'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='escaneo',
            index=models.Index(fields=['usuario', 'reconocido', '-fecha'], name='scanner_usuario_estado_idx'),
        ),
    ]
