# Generated by Django 6.0.6 on 2026-07-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id_comunicado', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/comunicados/')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'comunicado',
                'verbose_name_plural': 'comunicados',
                'ordering': ['-fecha', '-id_comunicado'],
            },
        ),
        migrations.CreateModel(
            name='ImagenPublicacion',
            fields=[
                ('id_imagen', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='noticias/publicaciones/')),
            ],
            options={
                'verbose_name': 'imagen de publicacion',
                'verbose_name_plural': 'imagenes de publicaciones',
                'ordering': ['id_imagen'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'publicacion',
                'verbose_name_plural': 'publicaciones',
                'ordering': ['-fecha', '-id_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/reportes/')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revision'), ('ATENDIDO', 'Atendido'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
            ],
            options={
                'verbose_name': 'reporte',
                'verbose_name_plural': 'reportes',
                'ordering': ['-fecha', '-id_reporte'],
            },
        ),
    ]
