# Generated by Django 6.0.6 on 2026-07-18 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id_atributo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'atributo',
                'verbose_name_plural': 'atributos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ave',
            fields=[
                ('id_ave', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=200)),
                ('etiqueta_caracteristica', models.CharField(max_length=100)),
                ('caracteristicas', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ave',
                'verbose_name_plural': 'aves',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FotoAve',
            fields=[
                ('id_foto', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='catalogo/aves/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('es_principal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'foto de ave',
                'verbose_name_plural': 'fotos de aves',
                'ordering': ['-es_principal', 'id_foto'],
            },
        ),
        migrations.CreateModel(
            name='AtributoAve',
            fields=[
                ('id_atributo_ave', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=250)),
                ('es_destacado', models.BooleanField(default=False)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_por_ave', to='catalogo.atributo')),
                ('ave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='catalogo.ave')),
            ],
            options={
                'verbose_name': 'atributo de ave',
                'verbose_name_plural': 'atributos de aves',
                'ordering': ['id_atributo_ave'],
            },
        ),
        migrations.CreateModel(
            name='AveEncontrada',
            fields=[
                ('id_ave_encontrada', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_encontrada', models.DateTimeField(auto_now_add=True)),
                ('ave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='catalogo.ave')),
            ],
            options={
                'verbose_name': 'ave encontrada',
                'verbose_name_plural': 'aves encontradas',
                'ordering': ['-fecha_encontrada', '-id_ave_encontrada'],
            },
        ),
    ]
