# Generated by Django 6.0.6 on 2026-07-18 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aveencontrada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aves_encontradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fotoave',
            name='ave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='catalogo.ave'),
        ),
        migrations.AddConstraint(
            model_name='atributoave',
            constraint=models.UniqueConstraint(fields=('ave', 'atributo'), name='catalogo_atributo_unico_por_ave'),
        ),
        migrations.AddConstraint(
            model_name='aveencontrada',
            constraint=models.UniqueConstraint(fields=('usuario', 'ave'), name='catalogo_ave_unica_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='fotoave',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('ave',), name='catalogo_una_foto_principal_por_ave'),
        ),
    ]
