# Generated by Django 6.0.6 on 2026-07-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_aveencontrada_usuario'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ave',
            index=models.Index(fields=['activa', 'nombre'], name='catalogo_activa_nombre_idx'),
        ),
    ]
