# Generated by Django 6.0.6 on 2026-07-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre'], 'verbose_name': 'usuario registrado', 'verbose_name_plural': 'usuarios registrados'},
        ),
    ]
