# Generated by Django 6.0.6 on 2026-07-18 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaAdministrativa',
            fields=[
            ],
            options={
                'verbose_name': 'administrador',
                'verbose_name_plural': 'administradores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuario.usuario',),
        ),
        migrations.CreateModel(
            name='CuentaAplicacion',
            fields=[
            ],
            options={
                'verbose_name': 'cuenta creada en la app',
                'verbose_name_plural': 'cuentas creadas en la app',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuario.usuario',),
        ),
    ]
