# Generated by Django 6.0.6 on 2026-07-18 07:26

import django.db.models.deletion
from django.db import migrations, models


def copiar_cuentas_de_aplicacion(apps, schema_editor):
    Administrador = apps.get_model('usuario', 'Usuario')
    CuentaAplicacion = apps.get_model('usuario', 'CuentaAplicacion')

    cuentas = Administrador.objects.filter(
        is_staff=False,
        is_superuser=False,
    ).values(
        'id_usuario',
        'nombre',
        'correo',
        'password',
        'is_active',
    )
    CuentaAplicacion.objects.bulk_create(
        [CuentaAplicacion(**cuenta) for cuenta in cuentas],
        ignore_conflicts=True,
    )

    schema_editor.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('usuario_cuenta_aplicacion', 'id_usuario'),
            COALESCE((SELECT MAX(id_usuario) FROM usuario_cuenta_aplicacion), 1),
            EXISTS(SELECT 1 FROM usuario_cuenta_aplicacion)
        )
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_cuentaadministrativa_cuentaaplicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuentaAplicacion',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre'], 'verbose_name': 'administrador', 'verbose_name_plural': 'administradores'},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario_administrador',
        ),
        migrations.CreateModel(
            name='CuentaAplicacion',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cuenta creada en la app',
                'verbose_name_plural': 'cuentas creadas en la app',
                'db_table': 'usuario_cuenta_aplicacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.RunPython(
            copiar_cuentas_de_aplicacion,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='SesionCuentaAplicacion',
            fields=[
                ('id_sesion', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_hash', models.CharField(max_length=64, unique=True)),
                ('refresh_hash', models.CharField(max_length=64, unique=True)),
                ('access_expira', models.DateTimeField()),
                ('refresh_expira', models.DateTimeField()),
                ('revocada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='usuario.cuentaaplicacion')),
            ],
            options={
                'verbose_name': 'sesion de la app',
                'verbose_name_plural': 'sesiones de la app',
                'db_table': 'usuario_sesion_aplicacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
