# Generated by Django 6.0.6 on 2026-07-18 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_eliminar_cuentas_app_de_administradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncuentaaplicacion',
            name='ultima_actividad',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
