# Generated by Django 6.0.6 on 2026-07-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id_conversacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Nueva conversacion', max_length=150)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'conversacion',
                'verbose_name_plural': 'conversaciones',
                'ordering': ['-id_conversacion'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.BigAutoField(primary_key=True, serialize=False)),
                ('emisor', models.CharField(choices=[('USUARIO', 'Usuario'), ('IA', 'Inteligencia artificial')], max_length=10)),
                ('mensaje', models.TextField()),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'ordering': ['id_mensaje'],
            },
        ),
    ]
